server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        use_sql_comments: true
        format_sql: true
        show_sql: true
    open-in-view: false

  output:
    ansi:
      enabled: always

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: on



jwt:
  key: f7f83hfh0sfgh3hasfcxvno23bo2r

springdoc:
  api-docs:
    version: openapi_3_0
    path: /api
  swagger-ui:
    path: /ui
    operations-sorter: alpha, method
